version: "3.9"

services:
  backend:
    image: backend_image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8081"
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__AppConnectionString: "Host=${HOST};User ID=${USER_ID};Password=${PASSWORD};Server=${SERVER};Port=${PORT};Database=${DATABASE};Pooling=${POOLING}"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets/:/root/.microsoft/usersecrets
      - ${USERPROFILE}/.aspnet/https:/root/.aspnet/https/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
